#pragma once

enum cstrike15_user_messages
{
    CS_UM_VGUIMenu = 1,
    CS_UM_Geiger = 2,
    CS_UM_Train = 3,
    CS_UM_HudText = 4,
    CS_UM_SayText = 5,
    CS_UM_SayText2 = 6,
    CS_UM_TextMsg = 7,
    CS_UM_HudMsg = 8,
    CS_UM_ResetHud = 9,
    CS_UM_GameTitle = 10,
    CS_UM_Shake = 12,
    CS_UM_Fade = 13,
    CS_UM_Rumble = 14,
    CS_UM_CloseCaption = 15,
    CS_UM_CloseCaptionDirect = 16,
    CS_UM_SendAudio = 17,
    CS_UM_RawAudio = 18,
    CS_UM_VoiceMask = 19,
    CS_UM_RequestState = 20,
    CS_UM_Damage = 21,
    CS_UM_RadioText = 22,
    CS_UM_HintText = 23,
    CS_UM_KeyHintText = 24,
    CS_UM_ProcessSpottedEntityUpdate = 25,
    CS_UM_ReloadEffect = 26,
    CS_UM_AdjustMoney = 27,
    CS_UM_UpdateTeamMoney = 28,
    CS_UM_StopSpectatorMode = 29,
    CS_UM_KillCam = 30,
    CS_UM_DesiredTimescale = 31,
    CS_UM_CurrentTimescale = 32,
    CS_UM_AchievementEvent = 33,
    CS_UM_MatchEndConditions = 34,
    CS_UM_DisconnectToLobby = 35,
    CS_UM_PlayerStatsUpdate = 36,
    CS_UM_DisplayInventory = 37,
    CS_UM_WarmupHasEnded = 38,
    CS_UM_ClientInfo = 39,
    CS_UM_XRankGet = 40,
    CS_UM_XRankUpd = 41,
    CS_UM_CallVoteFailed = 45,
    CS_UM_VoteStart = 46,
    CS_UM_VotePass = 47,
    CS_UM_VoteFailed = 48,
    CS_UM_VoteSetup = 49,
    CS_UM_ServerRankRevealAll = 50,
    CS_UM_SendLastKillerDamageToClient = 51,
    CS_UM_ServerRankUpdate = 52,
    CS_UM_ItemPickup = 53,
    CS_UM_ShowMenu = 54,
    CS_UM_BarTime = 55,
    CS_UM_AmmoDenied = 56,
    CS_UM_MarkAchievement = 57,
    CS_UM_MatchStatsUpdate = 58,
    CS_UM_ItemDrop = 59,
    CS_UM_GlowPropTurnOff = 60,
    CS_UM_SendPlayerItemDrops = 61,
    CS_UM_RoundBackupFilenames = 62,
    CS_UM_SendPlayerItemFound = 63,
    CS_UM_ReportHit = 64,
    CS_UM_XpUpdate = 65,
    CS_UM_QuestProgress = 66,
    CS_UM_ScoreLeaderboardData = 67,
    CS_UM_PlayerDecalDigitalSignature = 68,
    MAX_ECSTRIKE15USERMESSAGES
};

enum bone_flags
{
	BONE_FLAG_PHYSICALLY_SIMULATED = (1 << 0),
	BONE_FLAG_PHYSICS_PROCEDURAL = (1 << 1),
	BONE_FLAG_ALWAYS_PROCEDURAL = (1 << 2),
	BONE_FLAG_SCREEN_ALIGN_SPHERE = (1 << 3),
	BONE_FLAG_SCREEN_ALIGN_CYLINDER = (1 << 4),
	BONE_FLAG_CALCULATE_MASK = (1 << 5) - BONE_FLAG_PHYSICALLY_SIMULATED,
	BONE_FLAG_USED_BY_HITBOX = (1 << 8),
	BONE_FLAG_USED_BY_ATTACHMENT = (1 << 9),
	BONE_FLAG_USED_BY_VERTEX_LOD0 = (1 << 10),
	BONE_FLAG_USED_BY_VERTEX_LOD1 = (1 << 11),
	BONE_FLAG_USED_BY_VERTEX_LOD2 = (1 << 12),
	BONE_FLAG_USED_BY_VERTEX_LOD3 = (1 << 13),
	BONE_FLAG_USED_BY_VERTEX_LOD4 = (1 << 14),
	BONE_FLAG_USED_BY_VERTEX_LOD5 = (1 << 15),
	BONE_FLAG_USED_BY_VERTEX_LOD6 = (1 << 16),
	BONE_FLAG_USED_BY_VERTEX_LOD7 = (1 << 17),
	BONE_FLAG_USED_BY_BONE_MERGE = (1 << 18),
	BONE_FLAG_USED_BY_VERTEX_MASK = (BONE_FLAG_USED_BY_BONE_MERGE - BONE_FLAG_USED_BY_VERTEX_LOD0),
	BONE_FLAG_USED_BY_ANYTHING = (1 << 19) - BONE_FLAG_USED_BY_HITBOX,
	BONE_FLAG_USED_MASK = (1 << 19) - BONE_FLAG_USED_BY_HITBOX,
	BONE_FLAG_FIXED_ALIGNMENT = (1 << 20),
	BONE_FLAG_HAS_SAVEFRAME_POS = (1 << 21),
	BONE_FLAG_HAS_SAVEFRAME_ROT64 = (1 << 22),
	BONE_FLAG_HAS_SAVEFRAME_ROT32 = (1 << 23),
	BONE_FLAG_TYPE_MASK = 0x00F00000
};